name: ZAP-Lab-API-scan

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application for vulnerabilities
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.6.0
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://testphp.vulnweb.com/'
          #rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          issue_title: 'ZAP Lab API Scan Report'
